version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgis/postgis:15-3.3
    container_name: canna_postgres
    environment:
      POSTGRES_DB: canna_visits
      POSTGRES_USER: canna_user
      POSTGRES_PASSWORD: canna_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - canna_network
    restart: unless-stopped

  # Backend API Server
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: canna_api
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://canna_user:canna_password@postgres:5432/canna_visits
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRES_IN: 7d
      FRONTEND_URL: http://localhost:3000
      UPLOAD_DIR: /app/uploads
      MAX_FILE_SIZE: 10485760
    ports:
      - "3001:3001"
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - postgres
    networks:
      - canna_network
    restart: unless-stopped

  # Frontend Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: canna_frontend
    environment:
      VITE_API_BASE_URL: http://api:3001/api
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - canna_network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: canna_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - api
    networks:
      - canna_network
    restart: unless-stopped

volumes:
  postgres_data:
  uploads_data:

networks:
  canna_network:
    driver: bridge